import LocalizedStrings from 'react-localization';

const textContent = new LocalizedStrings({
    en: {
        landing: {
            header: 'CONSUMER-READY BLOCKCHAIN',
            orbsIsAPublic: 'Orbs is a public blockchain built for the needs of apps with millions of users,',
            fromSLA: 'from SLAs to adjustable fee models to on-demand capacity.',
            button: 'LEARN MORE'
        },
        navigation: {
            about: 'ABOUT',
            vision: 'VISION',
            technology: 'TECHNOLOGY',
            clients: 'CLIENTS',
            careers: 'CAREERS',
            team: 'TEAM',
            news: 'NEWS',
            contact: 'CONTACT',
            subscribe: 'SUBSCRIBE'
        },
        contactForm: {
            getInTouch: 'GET IN TOUCH',
            name: 'Name*',
            email: 'Email*',
            message: 'Message',
            send: 'SEND',
            backToSite: 'Back to site'
        },
        subscribeForm: {
            neverMiss: 'Never miss an update, sign up for the Orbs newsletter',
            yourEmail: 'Your Email',
            subscribe: 'Subscribe',
            pleaseFill: 'Please fill out this field'
        },
        aboutPage: {
            about: 'ABOUT',
            atOrbs: 'At Orbs, we’re helping to create a fairer economy.',
            weWantTo: 'We want to change the consumer space from one dominated by industry giants to one where businesses and consumers can own the value they create and benefit from sharing it.',
            wereBuilding: 'We’re building technology that’s pragmatic, based on real user requirements, and inspired by existing best practices.',
            weveIncorporated: 'We’ve incorporated these philosophies into our blockchain, the first built for the needs of large scale consumer applications. We’re making it possible for brands to launch disruptive, decentralized consumer applications.',
            theOrbsEco: 'THE ORBS ECOSYSTEM',
            hexaLabs: 'Hexa Labs - A decentralized solutions provider for established consumer brands',
            orbsIsCreating: 'Orbs is creating the infrastructure on which established consumer brands can launch large scale consumer apps to their millions of users.',
            hexaLabsOrbs: 'Hexa Labs, Orbs\’ sister company and business development arm, is helping these brands every step of the way with its strategic and technological expertise. Hexa Labs offers established brands strategic, product and development services for everything from ideation and technology solutions to understanding decentralized business models. Hexa Labs\' clients include 3 of 2017’s top 10 ICOs and has helped raise over $300 million. Clients include Kik, Sirin Labs, Endor and many others.',
            learnMore: 'Learn more about how Hexa Labs helps consumer brands transition to the blockchain',
            ourVision: 'OUR VISION'
        },
        visionPage: {
            vision: 'VISION',
            weWantTo: 'We want to help our customers create new business models that are fairer,',
            moreStable: 'more stable and offer a more empowering user experience.',
            by2020: 'By 2020, large scale consumer applications will have transitioned to the blockchain to bring decentralized',
            servicesTo: 'services to billions of users worldwide.',
            theChallengeIs: 'The challenge is providing them with an infrastructure addressing the multitude of requirements to make this transition possible.',
            untillNow: 'Until now, established consumer brands have been forced to avoid blockchain technology altogether or settle for infrastructure',
            thatDoesntScale: 'that doesn’t scale, fee structures that break business models and a degree of liability that a real-world business cannot accept.',
            aBlockchain: 'A BLOCKCHAIN BUILT FOR',
            RealWorldBuisness:'REAL-WORLD BUSINESSES',
            ourGoal: 'Our goal is to solve the infrastructure problem brands face when launching large scale decentralized applications',
            byProviding: 'by providing a blockchain Infrastructure as a Service (IaaS) tailored to their needs.',
            weStartedBy: 'We started by working with real applications serving millions of users, like Kik and others. We worked to',
            understandTheirNeeds: 'understand their needs - all of them - from engineering to business to legal. Once we understood their requirements,',
            didWeStartTo: 'did we start to build a solution to meet their current and future needs.',
            togetherWith: 'Together with our partners, we are enabling the transition of consumers to the new decentralized economy.',
            ourVisionIs: 'Our vision is to transform businesses',
            intoEcosystems: 'into ecosystems.',
            ourTechnology: 'OUR TECHNOLOGY'
        },
        technologyPage: {
            technology: 'TECHNOLOGY',
            theOrbsPlatformIsABlockchain: 'The Orbs platform is a public blockchain Infrastructure as a Service (IaaS) for large scale consumer',
            applications: 'applications. Orbs provides the infrastructure for decentralized applications in a similar manner to existing',
            cloudComputing: 'cloud computing platforms like AWS which provide the infrastructure for centralized applications.',
            theOrbsPlatformIsMadeUp: 'The Orbs platform is made up of two primary infrastructure offerings:',
            consensusBasedLeftFirst: 'Consensus-based decentralized compute',
            consensusBasedLeftSecond: 'services (aka smart contracts)',
            consensusBasedRightFirst: 'Consensus-based decentralized',
            consensusBasedRightSecond: 'storage services',
            theCoreDifference: 'The core difference between Orbs and other blockchains is that Orbs is built from the ground',
            upForTheConsumer: 'up for the consumer application market and tailored to its very specific set of requirements.',
            whitepaper: 'Whitepaper comming soon',
            architecture: 'ARCHITECTURE',
            consensusAlgorithm: 'CONSENSUS ALGORITHM',
            technicalPaper: 'Technical paper comming soon',
            virtualPrivate: 'VIRTUAL PRIVATE CHAIN',
            theOrbsPlatformSupports: 'The Orbs platform supports blockchain virtualization which provides the look and feel of a dedicated blockchain while running on top of public and shared network of nodes and enjoying security and full decentralization. The separation of the virtual resources from the underlying physical ones provide the Virtual Chains with isolation, quality of service, SLA (Service Level Agreement) and elastic resource capacity.',
            infrastructureMarketplace: 'INFRASTRUCTURE MARKETPLACE',
            theOrbsMarketplace: 'The Orbs marketplace will showcase specialized decentralized infrastructure providers that Orbs customers can choose from to deploy to their decentralized applications. Independent software providers will be able to offer decentralized flavors (like decentralized analytics) of their software that customers may already be using with their centralized applications. Orbs will provide API compatibility on the smart contract SDK layer and allow providers to rely on the Orbs consensus layer.',
            theseSpecialized: 'These specialized services will help create a fuller infrastructure ecosystem and provide value-added capabilities to the Orbs platform.',
            benefits: 'BENEFITS',
            theOrbsPlatformIsBuilt: 'The Orbs platform is built for consumer-scale computing adhering to clear',
            andPredictable: 'and predictable SLAs.',
            consumerScale: 'Consumer Scale',
            theNetworkIsDesigned: 'The network is designed for extreme scalability - serving hundreds of millions of users making billions of transactions per day.',
            serviceLevel: 'Service Level Agreement (SLA)',
            thePlatformIsBuilt: 'The platform is built for customers who expect a pre-defined level of service that they can rely on. Orbs offers different service tiers to suit different business requirements.',
            evolvingComplience: 'Evolving Compliance and Regulations',
            orbsOffers: 'Orbs offers comprehensive compliance - allowing consumer applications to meet current and evolving regulatory requirements. Orbs has an expandable regulatory model to suit the various regulations and liability challenges large businesses encounter.',
            modernDeployment: 'Modern Deployment Paradigms',
            largeScale: 'Large scale applications with millions of users cannot simply deploy or upgrade their application at once and hope for the best. Orbs offers the features necessary for manageable deployments, including: versions, migrations and multi-chains.',
            timeline: 'TIMELINE',
            commingSoon: 'COMMING SOON',
            ourClients: 'OUR CLIENTS'
        },
        clientsPage: {
            whatIsYour: 'WHAT IS YOUR',
            mission: 'MISSION?',
            letsAccomplish: 'Let’s accomplish your mission together',
        },
        careersPage: {
            doYouWantToBe: 'DO YOU WANT TO BE PART OF',
            theNextGeneration: 'THE NEXT GENERATION OF',
            blockchainTechnology: 'BLOCKCHAIN TECHNOLOGY?',
            wereLooking: 'We’re looking for people who are passionate about their work and excited',
            aboutTheFuture: 'about the future of blockchain technology.',
        },
        teamPage: {
            team: 'TEAM',
            orbsIsMadeUp: 'Orbs is made up of a diverse group of entrepreneurs, academics and',
            engineersKeeping: 'engineers keeping calm and working hard.'
        },
        newsPage: {
            twitterButtonFollow: 'Follow',
            media: 'MEDIA',
            pressKit: 'PressKit',
            twitterUpdates: 'Twitter Updates',
            mediumUpdates: 'Medium Updates',
            visitOrbsBlog: 'Visit Orbs Blog',
            fromTheMedia: 'From the media'
        },
        vacancy: {
            openPositions: 'OPEN POSITIONS',
            requiremants: 'Requirements',
            goodToHave: 'Good to Have',
            toApply: 'To apply',
            sendEmailTo: 'Send an email to',
            withYourCV: 'with your CV and the job title in the subject line'
        },
        footer: {
            allRightsReserved: 'All Rights Reserved to ORBS 2018',
            termOfUse: 'Term Of Use',
            privatPolicy: 'Privat Policy'
        }
    },
    'zh': {
        landing: {
            header: 'Test interface',
            paragraph: 'Orbs makes it possible for consumer brands to transition their millions of users to the blockchain',
            button: 'LEARN MORE'
        },
        navigation: {
            about: 'ABOUT',
            vision: 'VISION',
            technology: 'TECHNOLOGY',
            clients: 'CLIENTS',
            careers: 'CAREERS',
            team: 'TEAM',
            news: 'NEWS',
            contact: 'CONTACT',
            subscribe: 'SUBSCRIBE'
        },
        contactForm: {
            getInTouch: 'GET IN TOUCH',
            name: 'Name*',
            email: 'Email*',
            message: 'Message',
            send: 'SEND',
            backToSite: 'Back to site'
        },
        subscribeForm: {
            neverMiss: 'Never miss an update, sign up for the Orbs newsletter',
            yourEmail: 'Your Email',
            subscribe: 'Subscribe',
            pleaseFill: 'Please fill out this field'
        },
        aboutPage: {
            about: 'ABOUT',
            atOrbs: 'At Orbs, we’re helping to create a fairer economy.',
            weWantTo: 'We want to change the consumer space from one dominated by industry giants to one where businesses and consumers can own the value they create and benefit from sharing it.',
            wereBuilding: 'We’re building technology that’s pragmatic, based on real user requirements, and inspired by existing best practices.',
            weveIncorporated: 'We’ve incorporated these philosophies into our blockchain, the first built for the needs of large scale consumer applications. We’re making it possible for brands to launch disruptive, decentralized consumer applications.',
            theOrbsEco: 'THE ORBS ECOSYSTEM',
            hexaLabs: 'Hexa Labs - A decentralized solutions provider for established consumer brands',
            orbsIsCreating: 'Orbs is creating the infrastructure on which established consumer brands can launch large scale consumer apps to their millions of users.',
            hexaLabsOrbs: 'Hexa Labs, Orbs\’ sister company and business development arm, is helping these brands every step of the way with its strategic and technological expertise. Hexa Labs offers established brands strategic, product and development services for everything from ideation and technology solutions to understanding decentralized business models. Hexa Labs\' clients include 3 of 2017’s top 10 ICOs and has helped raise over $300 million. Clients include Kik, Sirin Labs, Endor and many others.',
            learnMore: 'Learn more about how Hexa Labs helps consumer brands transition to the blockchain',
            ourVision: 'OUR VISION'
        },
        visionPage: {
            vision: 'VISION',
            weWantTo: 'We want to help our customers create new business models that are fairer,',
            moreStable: 'more stable and offer a more empowering user experience.',
            by2020: 'By 2020, large scale consumer applications will have transitioned to the blockchain to bring decentralized',
            servicesTo: 'services to billions of users worldwide.',
            theChallengeIs: 'The challenge is providing them with an infrastructure addressing the multitude of requirements to make this transition possible.',
            untillNow: 'Until now, established consumer brands have been forced to avoid blockchain technology altogether or settle for infrastructure',
            thatDoesntScale: 'that doesn’t scale, fee structures that break business models and a degree of liability that a real-world business cannot accept.',
            aBlockchain: 'A BLOCKCHAIN BUILT FOR',
            RealWorldBuisness:'REAL-WORLD BUSINESSES',
            ourGoal: 'Our goal is to solve the infrastructure problem brands face when launching large scale decentralized applications',
            byProviding: 'by providing a blockchain Infrastructure as a Service (IaaS) tailored to their needs.',
            weStartedBy: 'We started by working with real applications serving millions of users, like Kik and others. We worked to',
            understandTheirNeeds: 'understand their needs - all of them - from engineering to business to legal. Once we understood their requirements,',
            didWeStartTo: 'did we start to build a solution to meet their current and future needs.',
            togetherWith: 'Together with our partners, we are enabling the transition of consumers to the new decentralized economy.',
            ourVisionIs: 'Our vision is to transform businesses',
            intoEcosystems: 'into ecosystems.',
            ourTechnology: 'OUR TECHNOLOGY'
        },
        technologyPage: {
            technology: 'TECHNOLOGY',
            theOrbsPlatformIsABlockchain: 'The Orbs platform is a public blockchain Infrastructure as a Service (IaaS) for large scale consumer',
            applications: 'applications. Orbs provides the infrastructure for decentralized applications in a similar manner to existing',
            cloudComputing: 'cloud computing platforms like AWS which provide the infrastructure for centralized applications.',
            theOrbsPlatformIsMadeUp: 'The Orbs platform is made up of two primary infrastructure offerings:',
            consensusBasedLeftFirst: 'Consensus-based decentralized compute',
            consensusBasedLeftSecond: 'services (aka smart contracts)',
            consensusBasedRightFirst: 'Consensus-based decentralized',
            consensusBasedRightSecond: 'storage services',
            theCoreDifference: 'The core difference between Orbs and other blockchains is that Orbs is built from the ground',
            upForTheConsumer: 'up for the consumer application market and tailored to its very specific set of requirements.',
            whitepaper: 'Whitepaper comming soon',
            architecture: 'ARCHITECTURE',
            consensusAlgorithm: 'CONSENSUS ALGORITHM',
            technicalPaper: 'Technical paper comming soon',
            virtualPrivate: 'VIRTUAL PRIVATE CHAIN',
            theOrbsPlatformSupports: 'The Orbs platform supports blockchain virtualization which provides the look and feel of a dedicated blockchain while running on top of public and shared network of nodes and enjoying security and full decentralization. The separation of the virtual resources from the underlying physical ones provide the Virtual Chains with isolation, quality of service, SLA (Service Level Agreement) and elastic resource capacity.',
            infrastructureMarketplace: 'INFRASTRUCTURE MARKETPLACE',
            theOrbsMarketplace: 'The Orbs marketplace will showcase specialized decentralized infrastructure providers that Orbs customers can choose from to deploy to their decentralized applications. Independent software providers will be able to offer decentralized flavors (like decentralized analytics) of their software that customers may already be using with their centralized applications. Orbs will provide API compatibility on the smart contract SDK layer and allow providers to rely on the Orbs consensus layer.',
            theseSpecialized: 'These specialized services will help create a fuller infrastructure ecosystem and provide value-added capabilities to the Orbs platform.',
            benefits: 'BENEFITS',
            theOrbsPlatformIsBuilt: 'The Orbs platform is built for consumer-scale computing adhering to clear',
            andPredictable: 'and predictable SLAs.',
            consumerScale: 'Consumer Scale',
            theNetworkIsDesigned: 'The network is designed for extreme scalability - serving hundreds of millions of users making billions of transactions per day.',
            serviceLevel: 'Service Level Agreement (SLA)',
            thePlatformIsBuilt: 'The platform is built for customers who expect a pre-defined level of service that they can rely on. Orbs offers different service tiers to suit different business requirements.',
            evolvingComplience: 'Evolving Compliance and Regulations',
            orbsOffers: 'Orbs offers comprehensive compliance - allowing consumer applications to meet current and evolving regulatory requirements. Orbs has an expandable regulatory model to suit the various regulations and liability challenges large businesses encounter.',
            modernDeployment: 'Modern Deployment Paradigms',
            largeScale: 'Large scale applications with millions of users cannot simply deploy or upgrade their application at once and hope for the best. Orbs offers the features necessary for manageable deployments, including: versions, migrations and multi-chains.',
            timeline: 'TIMELINE',
            commingSoon: 'COMMING SOON',
            ourClients: 'OUR CLIENTS'
        },
        clientsPage: {
            whatIsYour: 'WHAT IS YOUR',
            mission: 'MISSION?',
            letsAccomplish: 'Let’s accomplish your mission together',
        },
        careersPage: {
            doYouWantToBe: 'DO YOU WANT TO BE PART OF',
            theNextGeneration: 'THE NEXT GENERATION OF',
            blockchainTechnology: 'BLOCKCHAIN TECHNOLOGY?',
            wereLooking: 'We’re looking for people who are passionate about their work and excited',
            aboutTheFuture: 'about the future of blockchain technology.',
        },
        teamPage: {
            team: 'TEAM',
            orbsIsMadeUp: 'Orbs is made up of a diverse group of entrepreneurs, academics and',
            engineersKeeping: 'engineers keeping calm and working hard.'
        },
        newsPage: {
            media: 'MEDIA',
            pressKit: 'PressKit',
            twitterUpdates: 'Twitter Updates',
            mediumUpdates: 'Medium Updates',
            visitOrbsBlog: 'Visit Orbs Blog',
            fromTheMedia: 'From the media'
        },
        vacancy: {
            openPositions: 'OPEN POSITIONS',
            requiremants: 'Requirements',
            goodToHave: 'Good to Have',
            toApply: 'To apply',
            sendEmailTo: 'Send an email to',
            withYourCV: 'with your CV and the job title in the subject line'
        },
        footer: {
            allRightsReserved: 'All Rights Reserved to ORBS 2018',
            termOfUse: 'Term Of Use',
            privatPolicy: 'Privat Policy'
        }
    },
    'ko': {
        landing: {
            header: 'Test interface',
            paragraph: 'Orbs makes it possible for consumer brands to transition their millions of users to the blockchain',
            button: 'LEARN MORE'
        },
        navigation: {
            about: 'ABOUT',
            vision: 'VISION',
            technology: 'TECHNOLOGY',
            clients: 'CLIENTS',
            careers: 'CAREERS',
            team: 'TEAM',
            news: 'NEWS',
            contact: 'CONTACT',
            subscribe: 'SUBSCRIBE'
        },
        contactForm: {
            getInTouch: 'GET IN TOUCH',
            name: 'Name*',
            email: 'Email*',
            message: 'Message',
            send: 'SEND',
            backToSite: 'Back to site'
        },
        subscribeForm: {
            neverMiss: 'Never miss an update, sign up for the Orbs newsletter',
            yourEmail: 'Your Email',
            subscribe: 'Subscribe',
            pleaseFill: 'Please fill out this field'
        },
        aboutPage: {
            about: 'ABOUT',
            atOrbs: 'At Orbs, we’re helping to create a fairer economy.',
            weWantTo: 'We want to change the consumer space from one dominated by industry giants to one where businesses and consumers can own the value they create and benefit from sharing it.',
            wereBuilding: 'We’re building technology that’s pragmatic, based on real user requirements, and inspired by existing best practices.',
            weveIncorporated: 'We’ve incorporated these philosophies into our blockchain, the first built for the needs of large scale consumer applications. We’re making it possible for brands to launch disruptive, decentralized consumer applications.',
            theOrbsEco: 'THE ORBS ECOSYSTEM',
            hexaLabs: 'Hexa Labs - A decentralized solutions provider for established consumer brands',
            orbsIsCreating: 'Orbs is creating the infrastructure on which established consumer brands can launch large scale consumer apps to their millions of users.',
            hexaLabsOrbs: 'Hexa Labs, Orbs\’ sister company and business development arm, is helping these brands every step of the way with its strategic and technological expertise. Hexa Labs offers established brands strategic, product and development services for everything from ideation and technology solutions to understanding decentralized business models. Hexa Labs\' clients include 3 of 2017’s top 10 ICOs and has helped raise over $300 million. Clients include Kik, Sirin Labs, Endor and many others.',
            learnMore: 'Learn more about how Hexa Labs helps consumer brands transition to the blockchain',
            ourVision: 'OUR VISION'
        },
        visionPage: {
            vision: 'VISION',
            weWantTo: 'We want to help our customers create new business models that are fairer,',
            moreStable: 'more stable and offer a more empowering user experience.',
            by2020: 'By 2020, large scale consumer applications will have transitioned to the blockchain to bring decentralized',
            servicesTo: 'services to billions of users worldwide.',
            theChallengeIs: 'The challenge is providing them with an infrastructure addressing the multitude of requirements to make this transition possible.',
            untillNow: 'Until now, established consumer brands have been forced to avoid blockchain technology altogether or settle for infrastructure',
            thatDoesntScale: 'that doesn’t scale, fee structures that break business models and a degree of liability that a real-world business cannot accept.',
            aBlockchain: 'A BLOCKCHAIN BUILT FOR',
            RealWorldBuisness:'REAL-WORLD BUSINESSES',
            ourGoal: 'Our goal is to solve the infrastructure problem brands face when launching large scale decentralized applications',
            byProviding: 'by providing a blockchain Infrastructure as a Service (IaaS) tailored to their needs.',
            weStartedBy: 'We started by working with real applications serving millions of users, like Kik and others. We worked to',
            understandTheirNeeds: 'understand their needs - all of them - from engineering to business to legal. Once we understood their requirements,',
            didWeStartTo: 'did we start to build a solution to meet their current and future needs.',
            togetherWith: 'Together with our partners, we are enabling the transition of consumers to the new decentralized economy.',
            ourVisionIs: 'Our vision is to transform businesses',
            intoEcosystems: 'into ecosystems.',
            ourTechnology: 'OUR TECHNOLOGY'
        },
        technologyPage: {
            technology: 'TECHNOLOGY',
            theOrbsPlatformIsABlockchain: 'The Orbs platform is a public blockchain Infrastructure as a Service (IaaS) for large scale consumer',
            applications: 'applications. Orbs provides the infrastructure for decentralized applications in a similar manner to existing',
            cloudComputing: 'cloud computing platforms like AWS which provide the infrastructure for centralized applications.',
            theOrbsPlatformIsMadeUp: 'The Orbs platform is made up of two primary infrastructure offerings:',
            consensusBasedLeftFirst: 'Consensus-based decentralized compute',
            consensusBasedLeftSecond: 'services (aka smart contracts)',
            consensusBasedRightFirst: 'Consensus-based decentralized',
            consensusBasedRightSecond: 'storage services',
            theCoreDifference: 'The core difference between Orbs and other blockchains is that Orbs is built from the ground',
            upForTheConsumer: 'up for the consumer application market and tailored to its very specific set of requirements.',
            whitepaper: 'Whitepaper comming soon',
            architecture: 'ARCHITECTURE',
            consensusAlgorithm: 'CONSENSUS ALGORITHM',
            technicalPaper: 'Technical paper comming soon',
            virtualPrivate: 'VIRTUAL PRIVATE CHAIN',
            theOrbsPlatformSupports: 'The Orbs platform supports blockchain virtualization which provides the look and feel of a dedicated blockchain while running on top of public and shared network of nodes and enjoying security and full decentralization. The separation of the virtual resources from the underlying physical ones provide the Virtual Chains with isolation, quality of service, SLA (Service Level Agreement) and elastic resource capacity.',
            infrastructureMarketplace: 'INFRASTRUCTURE MARKETPLACE',
            theOrbsMarketplace: 'The Orbs marketplace will showcase specialized decentralized infrastructure providers that Orbs customers can choose from to deploy to their decentralized applications. Independent software providers will be able to offer decentralized flavors (like decentralized analytics) of their software that customers may already be using with their centralized applications. Orbs will provide API compatibility on the smart contract SDK layer and allow providers to rely on the Orbs consensus layer.',
            theseSpecialized: 'These specialized services will help create a fuller infrastructure ecosystem and provide value-added capabilities to the Orbs platform.',
            benefits: 'BENEFITS',
            theOrbsPlatformIsBuilt: 'The Orbs platform is built for consumer-scale computing adhering to clear',
            andPredictable: 'and predictable SLAs.',
            consumerScale: 'Consumer Scale',
            theNetworkIsDesigned: 'The network is designed for extreme scalability - serving hundreds of millions of users making billions of transactions per day.',
            serviceLevel: 'Service Level Agreement (SLA)',
            thePlatformIsBuilt: 'The platform is built for customers who expect a pre-defined level of service that they can rely on. Orbs offers different service tiers to suit different business requirements.',
            evolvingComplience: 'Evolving Compliance and Regulations',
            orbsOffers: 'Orbs offers comprehensive compliance - allowing consumer applications to meet current and evolving regulatory requirements. Orbs has an expandable regulatory model to suit the various regulations and liability challenges large businesses encounter.',
            modernDeployment: 'Modern Deployment Paradigms',
            largeScale: 'Large scale applications with millions of users cannot simply deploy or upgrade their application at once and hope for the best. Orbs offers the features necessary for manageable deployments, including: versions, migrations and multi-chains.',
            timeline: 'TIMELINE',
            commingSoon: 'COMMING SOON',
            ourClients: 'OUR CLIENTS'
        },
        clientsPage: {
            whatIsYour: 'WHAT IS YOUR',
            mission: 'MISSION?',
            letsAccomplish: 'Let’s accomplish your mission together',
        },
        careersPage: {
            doYouWantToBe: 'DO YOU WANT TO BE PART OF',
            theNextGeneration: 'THE NEXT GENERATION OF',
            blockchainTechnology: 'BLOCKCHAIN TECHNOLOGY?',
            wereLooking: 'We’re looking for people who are passionate about their work and excited',
            aboutTheFuture: 'about the future of blockchain technology.',
        },
        teamPage: {
            team: 'TEAM',
            orbsIsMadeUp: 'Orbs is made up of a diverse group of entrepreneurs, academics and',
            engineersKeeping: 'engineers keeping calm and working hard.'
        },
        newsPage: {
            media: 'MEDIA',
            pressKit: 'PressKit',
            twitterUpdates: 'Twitter Updates',
            mediumUpdates: 'Medium Updates',
            visitOrbsBlog: 'Visit Orbs Blog',
            fromTheMedia: 'From the media'
        },
        vacancy: {
            openPositions: 'OPEN POSITIONS',
            requiremants: 'Requirements',
            goodToHave: 'Good to Have',
            toApply: 'To apply',
            sendEmailTo: 'Send an email to',
            withYourCV: 'with your CV and the job title in the subject line'
        },
        footer: {
            allRightsReserved: 'All Rights Reserved to ORBS 2018',
            termOfUse: 'Term Of Use',
            privatPolicy: 'Privat Policy'
        }
    },
    'ja': {
        landing: {
            header: 'Test interface',
            paragraph: 'Orbs makes it possible for consumer brands to transition their millions of users to the blockchain',
            button: 'LEARN MORE'
        },
        navigation: {
            about: 'ABOUT',
            vision: 'VISION',
            technology: 'TECHNOLOGY',
            clients: 'CLIENTS',
            careers: 'CAREERS',
            team: 'TEAM',
            news: 'NEWS',
            contact: 'CONTACT',
            subscribe: 'SUBSCRIBE'
        },
        contactForm: {
            getInTouch: 'GET IN TOUCH',
            name: 'Name*',
            email: 'Email*',
            message: 'Message',
            send: 'SEND',
            backToSite: 'Back to site'
        },
        subscribeForm: {
            neverMiss: 'Never miss an update, sign up for the Orbs newsletter',
            yourEmail: 'Your Email',
            subscribe: 'Subscribe',
            pleaseFill: 'Please fill out this field'
        },
        aboutPage: {
            about: 'ABOUT',
            atOrbs: 'At Orbs, we’re helping to create a fairer economy.',
            weWantTo: 'We want to change the consumer space from one dominated by industry giants to one where businesses and consumers can own the value they create and benefit from sharing it.',
            wereBuilding: 'We’re building technology that’s pragmatic, based on real user requirements, and inspired by existing best practices.',
            weveIncorporated: 'We’ve incorporated these philosophies into our blockchain, the first built for the needs of large scale consumer applications. We’re making it possible for brands to launch disruptive, decentralized consumer applications.',
            theOrbsEco: 'THE ORBS ECOSYSTEM',
            hexaLabs: 'Hexa Labs - A decentralized solutions provider for established consumer brands',
            orbsIsCreating: 'Orbs is creating the infrastructure on which established consumer brands can launch large scale consumer apps to their millions of users.',
            hexaLabsOrbs: 'Hexa Labs, Orbs\’ sister company and business development arm, is helping these brands every step of the way with its strategic and technological expertise. Hexa Labs offers established brands strategic, product and development services for everything from ideation and technology solutions to understanding decentralized business models. Hexa Labs\' clients include 3 of 2017’s top 10 ICOs and has helped raise over $300 million. Clients include Kik, Sirin Labs, Endor and many others.',
            learnMore: 'Learn more about how Hexa Labs helps consumer brands transition to the blockchain',
            ourVision: 'OUR VISION'
        },
        visionPage: {
            vision: 'VISION',
            weWantTo: 'We want to help our customers create new business models that are fairer,',
            moreStable: 'more stable and offer a more empowering user experience.',
            by2020: 'By 2020, large scale consumer applications will have transitioned to the blockchain to bring decentralized',
            servicesTo: 'services to billions of users worldwide.',
            theChallengeIs: 'The challenge is providing them with an infrastructure addressing the multitude of requirements to make this transition possible.',
            untillNow: 'Until now, established consumer brands have been forced to avoid blockchain technology altogether or settle for infrastructure',
            thatDoesntScale: 'that doesn’t scale, fee structures that break business models and a degree of liability that a real-world business cannot accept.',
            aBlockchain: 'A BLOCKCHAIN BUILT FOR',
            RealWorldBuisness:'REAL-WORLD BUSINESSES',
            ourGoal: 'Our goal is to solve the infrastructure problem brands face when launching large scale decentralized applications',
            byProviding: 'by providing a blockchain Infrastructure as a Service (IaaS) tailored to their needs.',
            weStartedBy: 'We started by working with real applications serving millions of users, like Kik and others. We worked to',
            understandTheirNeeds: 'understand their needs - all of them - from engineering to business to legal. Once we understood their requirements,',
            didWeStartTo: 'did we start to build a solution to meet their current and future needs.',
            togetherWith: 'Together with our partners, we are enabling the transition of consumers to the new decentralized economy.',
            ourVisionIs: 'Our vision is to transform businesses',
            intoEcosystems: 'into ecosystems.',
            ourTechnology: 'OUR TECHNOLOGY'
        },
        technologyPage: {
            technology: 'TECHNOLOGY',
            theOrbsPlatformIsABlockchain: 'The Orbs platform is a public blockchain Infrastructure as a Service (IaaS) for large scale consumer',
            applications: 'applications. Orbs provides the infrastructure for decentralized applications in a similar manner to existing',
            cloudComputing: 'cloud computing platforms like AWS which provide the infrastructure for centralized applications.',
            theOrbsPlatformIsMadeUp: 'The Orbs platform is made up of two primary infrastructure offerings:',
            consensusBasedLeftFirst: 'Consensus-based decentralized compute',
            consensusBasedLeftSecond: 'services (aka smart contracts)',
            consensusBasedRightFirst: 'Consensus-based decentralized',
            consensusBasedRightSecond: 'storage services',
            theCoreDifference: 'The core difference between Orbs and other blockchains is that Orbs is built from the ground',
            upForTheConsumer: 'up for the consumer application market and tailored to its very specific set of requirements.',
            whitepaper: 'Whitepaper comming soon',
            architecture: 'ARCHITECTURE',
            consensusAlgorithm: 'CONSENSUS ALGORITHM',
            technicalPaper: 'Technical paper comming soon',
            virtualPrivate: 'VIRTUAL PRIVATE CHAIN',
            theOrbsPlatformSupports: 'The Orbs platform supports blockchain virtualization which provides the look and feel of a dedicated blockchain while running on top of public and shared network of nodes and enjoying security and full decentralization. The separation of the virtual resources from the underlying physical ones provide the Virtual Chains with isolation, quality of service, SLA (Service Level Agreement) and elastic resource capacity.',
            infrastructureMarketplace: 'INFRASTRUCTURE MARKETPLACE',
            theOrbsMarketplace: 'The Orbs marketplace will showcase specialized decentralized infrastructure providers that Orbs customers can choose from to deploy to their decentralized applications. Independent software providers will be able to offer decentralized flavors (like decentralized analytics) of their software that customers may already be using with their centralized applications. Orbs will provide API compatibility on the smart contract SDK layer and allow providers to rely on the Orbs consensus layer.',
            theseSpecialized: 'These specialized services will help create a fuller infrastructure ecosystem and provide value-added capabilities to the Orbs platform.',
            benefits: 'BENEFITS',
            theOrbsPlatformIsBuilt: 'The Orbs platform is built for consumer-scale computing adhering to clear',
            andPredictable: 'and predictable SLAs.',
            consumerScale: 'Consumer Scale',
            theNetworkIsDesigned: 'The network is designed for extreme scalability - serving hundreds of millions of users making billions of transactions per day.',
            serviceLevel: 'Service Level Agreement (SLA)',
            thePlatformIsBuilt: 'The platform is built for customers who expect a pre-defined level of service that they can rely on. Orbs offers different service tiers to suit different business requirements.',
            evolvingComplience: 'Evolving Compliance and Regulations',
            orbsOffers: 'Orbs offers comprehensive compliance - allowing consumer applications to meet current and evolving regulatory requirements. Orbs has an expandable regulatory model to suit the various regulations and liability challenges large businesses encounter.',
            modernDeployment: 'Modern Deployment Paradigms',
            largeScale: 'Large scale applications with millions of users cannot simply deploy or upgrade their application at once and hope for the best. Orbs offers the features necessary for manageable deployments, including: versions, migrations and multi-chains.',
            timeline: 'TIMELINE',
            commingSoon: 'COMMING SOON',
            ourClients: 'OUR CLIENTS'
        },
        clientsPage: {
            whatIsYour: 'WHAT IS YOUR',
            mission: 'MISSION?',
            letsAccomplish: 'Let’s accomplish your mission together',
        },
        careersPage: {
            doYouWantToBe: 'DO YOU WANT TO BE PART OF',
            theNextGeneration: 'THE NEXT GENERATION OF',
            blockchainTechnology: 'BLOCKCHAIN TECHNOLOGY?',
            wereLooking: 'We’re looking for people who are passionate about their work and excited',
            aboutTheFuture: 'about the future of blockchain technology.',
        },
        teamPage: {
            team: 'TEAM',
            orbsIsMadeUp: 'Orbs is made up of a diverse group of entrepreneurs, academics and',
            engineersKeeping: 'engineers keeping calm and working hard.'
        },
        newsPage: {
            media: 'MEDIA',
            pressKit: 'PressKit',
            twitterUpdates: 'Twitter Updates',
            mediumUpdates: 'Medium Updates',
            visitOrbsBlog: 'Visit Orbs Blog',
            fromTheMedia: 'From the media'
        },
        vacancy: {
            openPositions: 'OPEN POSITIONS',
            requiremants: 'Requirements',
            goodToHave: 'Good to Have',
            toApply: 'To apply',
            sendEmailTo: 'Send an email to',
            withYourCV: 'with your CV and the job title in the subject line'
        },
        footer: {
            allRightsReserved: 'All Rights Reserved to ORBS 2018',
            termOfUse: 'Term Of Use',
            privatPolicy: 'Privat Policy'
        }
    }
    
});

export default textContent;